### ISSUE TITLE
Porting to Python 3

### ISSUE THREAD

**Issue by jacopofar** [datquocnguyen/RDRPOSTagger#10]
Hello,
I've ported the script to Python 3, it's [here](https://github.com/jacopofar/RDRPOSTagger-python-3), you may want to link it or get it back as a git branch.

Unfortunately, the code does not work on Python 2

**Comment by thuvh** [comment]
you should fork this repository, then fix some incompatible code. Then make a pull request. I think it is a better way to contribute and credit the author of this postagger

**Comment by jacopofar** [comment]
The problem is that my changes break the compatibility with Python 2. I forked the repo, but a PR+merge would break it for Python 2 users.
