### ISSUE TITLE
Tags meaning

### ISSUE THREAD

**Issue by SilvioMessi** [datquocnguyen/RDRPOSTagger#12]
Hi! 
Where I can find a list with the meaning of the tags?

Thank you,
Silvio

**Comment by datquocnguyen** [comment]
Hi, 
For fine-grained POS tags, the references section in http://rdrpostagger.sourceforge.net/ show the links to corpora used to train tagging models. These links should lead you to the meanings of POS tags.

For universal POS tags, you can find at here: http://universaldependencies.org/u/pos/index.html
