### ISSUE TITLE
English and Vietnamese Pre-trained Pre-trained Model (POS+MORPH)

### ISSUE THREAD

**Issue by alain75007** [datquocnguyen/RDRPOSTagger#3]
Hi, thanks for this great work.
How to get English and Vietnamese Pre-trained models for combined POS and morphological (POS+MORPH) tagging?
Best regards,
A.

**Comment by datquocnguyen** [comment]
Hi, 
We did not find any POS+MORPH-annotated corpus for both English and Vietnamese. 
So we could not provide pre-trained POS+MORPH tagging models for English and Vietnamese.
