### ISSUE TITLE
Add a setup.py file so "pip" can be used to install

### ISSUE THREAD

**Issue by EmilStenstrom** [datquocnguyen/RDRPOSTagger#4]
I was looking to quickly try your library (which looks great) by installing it with python-pip. Problem is, it doesn't work unless you have setup.py file that describes the project. 

Adding a file is easy, here's an example from one of my projects: https://github.com/EmilStenstrom/python-nutshell/blob/master/setup.py

After this is done your project can be installed by typing:
```
pip install https://github.com/datquocnguyen/RDRPOSTagger/archive/master.zip
```

If you also want to reserve a name and make your project even easier to install you could publish it on PyPI. Then installation would be as easy as:

```
pip install RDRPOSTagger
```

Let me know if I can do anything to help you.

**Comment by datquocnguyen** [comment]
Hi,

Thank you very much for your interests in RDRPOSTagger. 

I would like to keep my project the same as it is since I expect it will help both Python and Java users.

Best,

Dat.
