### ISSUE TITLE
Slimmed down version of RDRPOSTagger

### ISSUE THREAD

**Issue by EmilStenstrom** [datquocnguyen/RDRPOSTagger#6]
Hi! I'm planning to do a slimmed down, easy to use version of RDRPosTagger. The idea is to simplify the projekt to only deal with UniPOS tagging with those models and remove everything else, including training, and non-UniPOS models. I will also remove the java version.

I will work on it as a fork of this project, hosted here: https://github.com/EmilStenstrom/RDRPOSTagger/

My idea is that this will make the code easier to read, and by simplifying it also easier to use. I have an idea of how I can use this commercially at the company I work with.

Are you ok with this? I see you have chosen the GNU license, so it looks that way, but I just want to be sure.

**Comment by EmilStenstrom** [comment]
Hi again,

Would you be interested in taking over development of RippleTagger? I'm guessing you will make model updates, and I would love to give you commit access to RippleTagger if you would like to keep syncing updates there.

(RippleTagger is still your code, just with a simplified codebase)

**Comment by datquocnguyen** [comment]
Hi,

I only made a very minor change to the tagging part (https://github.com/datquocnguyen/RDRPOSTagger/commit/bdc0b8b14b05e17c27ce5baff643fbb24e87ccff), so there is no need of updating pre-trained models.

Best,
Dat.
